language: objective-c
osx_image: xcode10.1

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=VirgilE3Kit.xcodeproj
    - IOS_SDK=iphonesimulator12.1
    - MACOS_SDK=macosx10.14
    - TVOS_SDK=appletvsimulator12.1
    - WATCHOS_SDK=watchsimulator5.1
    - FRAMEWORK_NAME=VirgilE3Kit
    - REPO=VirgilSecurity/virgil-e3kit-x
    - REPO_PATH=https://github.com/VirgilSecurity/virgil-e3kit-x.git

  matrix:
    - DESTINATION=""                                         PREFIX=""         SDK=""              BUILD="0"  PUBLISH_CARTHAGE="YES"  CARTHAGE_PLATFORM_NAME="Mac"      PUBLISH_POD="YES" POD_LIB_LINT="YES"  PUBLISH_DOCS="YES"  SWIFT_LINT="YES"
    - DESTINATION="OS=12.1,name=iPhone SE"                   PREFIX="iOS"      SDK="$IOS_SDK"      BUILD="2"  PUBLISH_CARTHAGE="NO"   CARTHAGE_PLATFORM_NAME="iOS"      PUBLISH_POD="NO"  POD_LIB_LINT="NO"   PUBLISH_DOCS="NO"   SWIFT_LINT="NO"
    - DESTINATION="arch=x86_64"                              PREFIX="macOS"    SDK="$MACOS_SDK"    BUILD="2"  PUBLISH_CARTHAGE="NO"   CARTHAGE_PLATFORM_NAME="Mac"      PUBLISH_POD="NO"  POD_LIB_LINT="NO"   PUBLISH_DOCS="NO"   SWIFT_LINT="NO"
    - DESTINATION="OS=12.1,name=Apple TV 4K"                 PREFIX="tvOS"     SDK="$TVOS_SDK"     BUILD="2"  PUBLISH_CARTHAGE="NO"   CARTHAGE_PLATFORM_NAME="tvOS"     PUBLISH_POD="NO"  POD_LIB_LINT="NO"   PUBLISH_DOCS="NO"   SWIFT_LINT="NO"
    - DESTINATION="OS=5.1,name=Apple Watch Series 4 - 44mm"  PREFIX="watchOS"  SDK="$WATCHOS_SDK"  BUILD="1"  PUBLISH_CARTHAGE="NO"   CARTHAGE_PLATFORM_NAME="watchOS"  PUBLISH_POD="NO"  POD_LIB_LINT="NO"   PUBLISH_DOCS="NO"   SWIFT_LINT="NO"


before_install:
  - openssl aes-256-cbc -K $encrypted_a7b6c41d0d44_key -iv $encrypted_a7b6c41d0d44_iv -in TestConfig.plist.enc -out TestConfig.plist -d
  - set -e
  - set -o pipefail
  - brew update
  - brew outdated carthage || brew upgrade carthage

script:
  - mkdir Tests/Data
  - mv -f TestConfig.plist Tests/Data/TestConfig.plist

  - carthage version
  - carthage bootstrap --platform ${CARTHAGE_PLATFORM_NAME}

  - |
    if [ $SWIFT_LINT == "YES" ]; then
      brew outdated swiftlint || brew upgrade swiftlint
      swiftlint
    fi

  - SCHEME="VirgilE3Kit ${PREFIX}"
  
  - |
    if [ $BUILD == "2" ]; then
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean build-for-testing | xcpretty;
      # Run Tests
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test-without-building | xcpretty;
    elif [ $BUILD == "1" ]; then
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;
    fi

  # Check pod lib
  - if [ $POD_LIB_LINT == "YES" ]; then
      gem install cocoapods --pre;
      pod repo update;
      pod lib lint;
    fi

  # Build with carthage
  - if [ $PUBLISH_CARTHAGE == "YES" ]; then
      carthage build --no-skip-current;
      carthage archive
    fi

deploy:
  # Upload framework to gh-releases for carthage
  - provider: releases
    api_key: $GITHUB_ACCESS_TOKEN
    file: $FRAMEWORK_NAME.framework.zip
    skip_cleanup: true
    on:
      repo: $REPO
      tags: true
      condition: $PUBLISH_CARTHAGE = "YES"
